name: insp_converter
environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  ffmpeg_kit_flutter_full: ^6.0.3
  file_picker: ^8.1.4
  path: ^1.9.0
flutter:
  uses-material-design: true
